### PR TITLE
Fix HEVC NAL parsing and RTP de/packetization

### LINKED ISSUE #1392: HEVC/H.265 NAL Unit type depacketization is wrong?
I observed this miscalculation of the actual HEVC NAL type from 38 -> 36 causing `alignment_bit_equal_to_one=0` in ffmpeg, and subsequent packets constructed into frames are corrupted (can't find POC).

might have something to do with these lines:
https://github.com/sipsorcery-org/sipsorcery/blob/268e697e59fd47ff8a095da4d0078bb8c293c191/src/net/RTP/Packetisation/H265Depacketiser.cs#L189-L204

I don't know about the RFCs or the ITU standard to understand how to fix it.
Asking ChatGPT just confuses and doesn't help at all.

ADD:
The above was when not using `CreateAggregated()`, I must add this when using it:
```c#
if (nalCount > 0 && newNalList.Count == 0)
{
    newNalList.Add(new H265Nal(aggregated.ToArray(), aggregatedLast));
}
```
It's now miscalculating from 38 -> 76 and still causing `Could not find ref with POC 0`.

I got this using the `trace_headers` bitstream filter after RTP->frame constructing into FFmpeg:

<details>
<summary>'trace_headers' bitstream filter on receiver side</summary>

```
info: program[0]
      (o)=> SEND 6723
info: sipsorcery[0]
      (out) SEND 119(1/2)
info: sipsorcery[0]
      (out) SEND 6595(2/2)
info: program[0]
      =>(i) RECV 6724
[trace_headers @ 000001b104a32a00] Packet: 6788 bytes, no pts, no dts.
[trace_headers @ 000001b104a32a00] Video Parameter Set
[trace_headers @ 000001b104a32a00] 0           forbidden_zero_bit                                          0 = 0
[trace_headers @ 000001b104a32a00] 1           nal_unit_type                                          100000 = 32
[trace_headers @ 000001b104a32a00] 7           nuh_layer_id                                           000000 = 0
[trace_headers @ 000001b104a32a00] 13          nuh_temporal_id_plus1                                     001 = 1
[trace_headers @ 000001b104a32a00] 16          vps_video_parameter_set_id                               0000 = 0
[trace_headers @ 000001b104a32a00] 20          vps_base_layer_internal_flag                                1 = 1
[trace_headers @ 000001b104a32a00] 21          vps_base_layer_available_flag                               1 = 1
[trace_headers @ 000001b104a32a00] 22          vps_max_layers_minus1                                  000000 = 0
[trace_headers @ 000001b104a32a00] 28          vps_max_sub_layers_minus1                                 000 = 0
[trace_headers @ 000001b104a32a00] 31          vps_temporal_id_nesting_flag                                1 = 1
[trace_headers @ 000001b104a32a00] 32          vps_reserved_0xffff_16bits                   1111111111111111 = 65535
[trace_headers @ 000001b104a32a00] 48          general_profile_space                                      00 = 0
[trace_headers @ 000001b104a32a00] 50          general_tier_flag                                           0 = 0
[trace_headers @ 000001b104a32a00] 51          general_profile_idc                                     00001 = 1
[trace_headers @ 000001b104a32a00] 56          general_profile_compatibility_flag[0]                       0 = 0
[trace_headers @ 000001b104a32a00] 57          general_profile_compatibility_flag[1]                       1 = 1
[trace_headers @ 000001b104a32a00] 58          general_profile_compatibility_flag[2]                       0 = 0
[trace_headers @ 000001b104a32a00] 59          general_profile_compatibility_flag[3]                       0 = 0
[trace_headers @ 000001b104a32a00] 60          general_profile_compatibility_flag[4]                       0 = 0
[trace_headers @ 000001b104a32a00] 61          general_profile_compatibility_flag[5]                       0 = 0
[trace_headers @ 000001b104a32a00] 62          general_profile_compatibility_flag[6]                       0 = 0
[trace_headers @ 000001b104a32a00] 63          general_profile_compatibility_flag[7]                       0 = 0
[trace_headers @ 000001b104a32a00] 64          general_profile_compatibility_flag[8]                       0 = 0
[trace_headers @ 000001b104a32a00] 65          general_profile_compatibility_flag[9]                       0 = 0
[trace_headers @ 000001b104a32a00] 66          general_profile_compatibility_flag[10]                      0 = 0
[trace_headers @ 000001b104a32a00] 67          general_profile_compatibility_flag[11]                      0 = 0
[trace_headers @ 000001b104a32a00] 68          general_profile_compatibility_flag[12]                      0 = 0
[trace_headers @ 000001b104a32a00] 69          general_profile_compatibility_flag[13]                      0 = 0
[trace_headers @ 000001b104a32a00] 70          general_profile_compatibility_flag[14]                      0 = 0
[trace_headers @ 000001b104a32a00] 71          general_profile_compatibility_flag[15]                      0 = 0
[trace_headers @ 000001b104a32a00] 72          general_profile_compatibility_flag[16]                      0 = 0
[trace_headers @ 000001b104a32a00] 73          general_profile_compatibility_flag[17]                      0 = 0
[trace_headers @ 000001b104a32a00] 74          general_profile_compatibility_flag[18]                      0 = 0
[trace_headers @ 000001b104a32a00] 75          general_profile_compatibility_flag[19]                      0 = 0
[trace_headers @ 000001b104a32a00] 76          general_profile_compatibility_flag[20]                      0 = 0
[trace_headers @ 000001b104a32a00] 77          general_profile_compatibility_flag[21]                      0 = 0
[trace_headers @ 000001b104a32a00] 78          general_profile_compatibility_flag[22]                      0 = 0
[trace_headers @ 000001b104a32a00] 79          general_profile_compatibility_flag[23]                      0 = 0
[trace_headers @ 000001b104a32a00] 80          general_profile_compatibility_flag[24]                      0 = 0
[trace_headers @ 000001b104a32a00] 81          general_profile_compatibility_flag[25]                      0 = 0
[trace_headers @ 000001b104a32a00] 82          general_profile_compatibility_flag[26]                      0 = 0
[trace_headers @ 000001b104a32a00] 83          general_profile_compatibility_flag[27]                      0 = 0
[trace_headers @ 000001b104a32a00] 84          general_profile_compatibility_flag[28]                      0 = 0
[trace_headers @ 000001b104a32a00] 85          general_profile_compatibility_flag[29]                      0 = 0
[trace_headers @ 000001b104a32a00] 86          general_profile_compatibility_flag[30]                      0 = 0
[trace_headers @ 000001b104a32a00] 87          general_profile_compatibility_flag[31]                      0 = 0
[trace_headers @ 000001b104a32a00] 88          general_progressive_source_flag                             1 = 1
[trace_headers @ 000001b104a32a00] 89          general_interlaced_source_flag                              0 = 0
[trace_headers @ 000001b104a32a00] 90          general_non_packed_constraint_flag                          0 = 0
[trace_headers @ 000001b104a32a00] 91          general_frame_only_constraint_flag                          1 = 1
[trace_headers @ 000001b104a32a00] 92          general_reserved_zero_43bits         000000000000000000000000 = 0
[trace_headers @ 000001b104a32a00] 116         general_reserved_zero_43bits              0000000000000000000 = 0
[trace_headers @ 000001b104a32a00] 135         general_inbld_flag                                          0 = 0
[trace_headers @ 000001b104a32a00] 136         general_level_idc                                    00111111 = 63
[trace_headers @ 000001b104a32a00] 144         vps_sub_layer_ordering_info_present_flag                    0 = 0
[trace_headers @ 000001b104a32a00] 145         vps_max_dec_pic_buffering_minus1[0]                     00101 = 4
[trace_headers @ 000001b104a32a00] 150         vps_max_num_reorder_pics[0]                             00100 = 3
[trace_headers @ 000001b104a32a00] 155         vps_max_latency_increase_plus1[0]                           1 = 0
[trace_headers @ 000001b104a32a00] 156         vps_max_layer_id                                       000000 = 0
[trace_headers @ 000001b104a32a00] 162         vps_num_layer_sets_minus1                                   1 = 0
[trace_headers @ 000001b104a32a00] 163         vps_timing_info_present_flag                                1 = 1
[trace_headers @ 000001b104a32a00] 164         vps_num_units_in_tick        00000000000000000000000000000001 = 1
[trace_headers @ 000001b104a32a00] 196         vps_time_scale               00000000000000000000000000011101 = 29
[trace_headers @ 000001b104a32a00] 228         vps_poc_proportional_to_timing_flag                         0 = 0
[trace_headers @ 000001b104a32a00] 229         vps_num_hrd_parameters                                      1 = 0
[trace_headers @ 000001b104a32a00] 230         vps_extension_flag                                          0 = 0
[trace_headers @ 000001b104a32a00] 231         rbsp_stop_one_bit                                           1 = 1
[trace_headers @ 000001b104a32a00] Sequence Parameter Set
[trace_headers @ 000001b104a32a00] 0           forbidden_zero_bit                                          0 = 0
[trace_headers @ 000001b104a32a00] 1           nal_unit_type                                          100001 = 33
[trace_headers @ 000001b104a32a00] 7           nuh_layer_id                                           000000 = 0
[trace_headers @ 000001b104a32a00] 13          nuh_temporal_id_plus1                                     001 = 1
[trace_headers @ 000001b104a32a00] 16          sps_video_parameter_set_id                               0000 = 0
[trace_headers @ 000001b104a32a00] 20          sps_max_sub_layers_minus1                                 000 = 0
[trace_headers @ 000001b104a32a00] 23          sps_temporal_id_nesting_flag                                1 = 1
[trace_headers @ 000001b104a32a00] 24          general_profile_space                                      00 = 0
[trace_headers @ 000001b104a32a00] 26          general_tier_flag                                           0 = 0
[trace_headers @ 000001b104a32a00] 27          general_profile_idc                                     00001 = 1
[trace_headers @ 000001b104a32a00] 32          general_profile_compatibility_flag[0]                       0 = 0
[trace_headers @ 000001b104a32a00] 33          general_profile_compatibility_flag[1]                       1 = 1
[trace_headers @ 000001b104a32a00] 34          general_profile_compatibility_flag[2]                       0 = 0
[trace_headers @ 000001b104a32a00] 35          general_profile_compatibility_flag[3]                       0 = 0
[trace_headers @ 000001b104a32a00] 36          general_profile_compatibility_flag[4]                       0 = 0
[trace_headers @ 000001b104a32a00] 37          general_profile_compatibility_flag[5]                       0 = 0
[trace_headers @ 000001b104a32a00] 38          general_profile_compatibility_flag[6]                       0 = 0
[trace_headers @ 000001b104a32a00] 39          general_profile_compatibility_flag[7]                       0 = 0
[trace_headers @ 000001b104a32a00] 40          general_profile_compatibility_flag[8]                       0 = 0
[trace_headers @ 000001b104a32a00] 41          general_profile_compatibility_flag[9]                       0 = 0
[trace_headers @ 000001b104a32a00] 42          general_profile_compatibility_flag[10]                      0 = 0
[trace_headers @ 000001b104a32a00] 43          general_profile_compatibility_flag[11]                      0 = 0
[trace_headers @ 000001b104a32a00] 44          general_profile_compatibility_flag[12]                      0 = 0
[trace_headers @ 000001b104a32a00] 45          general_profile_compatibility_flag[13]                      0 = 0
[trace_headers @ 000001b104a32a00] 46          general_profile_compatibility_flag[14]                      0 = 0
[trace_headers @ 000001b104a32a00] 47          general_profile_compatibility_flag[15]                      0 = 0
[trace_headers @ 000001b104a32a00] 48          general_profile_compatibility_flag[16]                      0 = 0
[trace_headers @ 000001b104a32a00] 49          general_profile_compatibility_flag[17]                      0 = 0
[trace_headers @ 000001b104a32a00] 50          general_profile_compatibility_flag[18]                      0 = 0
[trace_headers @ 000001b104a32a00] 51          general_profile_compatibility_flag[19]                      0 = 0
[trace_headers @ 000001b104a32a00] 52          general_profile_compatibility_flag[20]                      0 = 0
[trace_headers @ 000001b104a32a00] 53          general_profile_compatibility_flag[21]                      0 = 0
[trace_headers @ 000001b104a32a00] 54          general_profile_compatibility_flag[22]                      0 = 0
[trace_headers @ 000001b104a32a00] 55          general_profile_compatibility_flag[23]                      0 = 0
[trace_headers @ 000001b104a32a00] 56          general_profile_compatibility_flag[24]                      0 = 0
[trace_headers @ 000001b104a32a00] 57          general_profile_compatibility_flag[25]                      0 = 0
[trace_headers @ 000001b104a32a00] 58          general_profile_compatibility_flag[26]                      0 = 0
[trace_headers @ 000001b104a32a00] 59          general_profile_compatibility_flag[27]                      0 = 0
[trace_headers @ 000001b104a32a00] 60          general_profile_compatibility_flag[28]                      0 = 0
[trace_headers @ 000001b104a32a00] 61          general_profile_compatibility_flag[29]                      0 = 0
[trace_headers @ 000001b104a32a00] 62          general_profile_compatibility_flag[30]                      0 = 0
[trace_headers @ 000001b104a32a00] 63          general_profile_compatibility_flag[31]                      0 = 0
[trace_headers @ 000001b104a32a00] 64          general_progressive_source_flag                             1 = 1
[trace_headers @ 000001b104a32a00] 65          general_interlaced_source_flag                              0 = 0
[trace_headers @ 000001b104a32a00] 66          general_non_packed_constraint_flag                          0 = 0
[trace_headers @ 000001b104a32a00] 67          general_frame_only_constraint_flag                          1 = 1
[trace_headers @ 000001b104a32a00] 68          general_reserved_zero_43bits         000000000000000000000000 = 0
[trace_headers @ 000001b104a32a00] 92          general_reserved_zero_43bits              0000000000000000000 = 0
[trace_headers @ 000001b104a32a00] 111         general_inbld_flag                                          0 = 0
[trace_headers @ 000001b104a32a00] 112         general_level_idc                                    00111111 = 63
[trace_headers @ 000001b104a32a00] 120         sps_seq_parameter_set_id                                    1 = 0
[trace_headers @ 000001b104a32a00] 121         chroma_format_idc                                         010 = 1
[trace_headers @ 000001b104a32a00] 124         pic_width_in_luma_samples                 0000000001000100001 = 544
[trace_headers @ 000001b104a32a00] 143         pic_height_in_luma_samples                  00000000101101001 = 360
[trace_headers @ 000001b104a32a00] 160         conformance_window_flag                                     1 = 1
[trace_headers @ 000001b104a32a00] 161         conf_win_left_offset                                        1 = 0
[trace_headers @ 000001b104a32a00] 162         conf_win_right_offset                                     011 = 2
[trace_headers @ 000001b104a32a00] 165         conf_win_top_offset                                         1 = 0
[trace_headers @ 000001b104a32a00] 166         conf_win_bottom_offset                                      1 = 0
[trace_headers @ 000001b104a32a00] 167         bit_depth_luma_minus8                                       1 = 0
[trace_headers @ 000001b104a32a00] 168         bit_depth_chroma_minus8                                     1 = 0
[trace_headers @ 000001b104a32a00] 169         log2_max_pic_order_cnt_lsb_minus4                       00100 = 3
[trace_headers @ 000001b104a32a00] 174         sps_sub_layer_ordering_info_present_flag                    0 = 0
[trace_headers @ 000001b104a32a00] 175         sps_max_dec_pic_buffering_minus1[0]                     00101 = 4
[trace_headers @ 000001b104a32a00] 180         sps_max_num_reorder_pics[0]                             00100 = 3
[trace_headers @ 000001b104a32a00] 185         sps_max_latency_increase_plus1[0]                           1 = 0
[trace_headers @ 000001b104a32a00] 186         log2_min_luma_coding_block_size_minus3                      1 = 0
[trace_headers @ 000001b104a32a00] 187         log2_diff_max_min_luma_coding_block_size                00100 = 3
[trace_headers @ 000001b104a32a00] 192         log2_min_luma_transform_block_size_minus2                   1 = 0
[trace_headers @ 000001b104a32a00] 193         log2_diff_max_min_luma_transform_block_size             00100 = 3
[trace_headers @ 000001b104a32a00] 198         max_transform_hierarchy_depth_inter                       011 = 2
[trace_headers @ 000001b104a32a00] 201         max_transform_hierarchy_depth_intra                       011 = 2
[trace_headers @ 000001b104a32a00] 204         scaling_list_enabled_flag                                   0 = 0
[trace_headers @ 000001b104a32a00] 205         amp_enabled_flag                                            1 = 1
[trace_headers @ 000001b104a32a00] 206         sample_adaptive_offset_enabled_flag                         1 = 1
[trace_headers @ 000001b104a32a00] 207         pcm_enabled_flag                                            0 = 0
[trace_headers @ 000001b104a32a00] 208         num_short_term_ref_pic_sets                           0001001 = 8
[trace_headers @ 000001b104a32a00] 215         num_negative_pics                                       00100 = 3
[trace_headers @ 000001b104a32a00] 220         num_positive_pics                                         010 = 1
[trace_headers @ 000001b104a32a00] 223         delta_poc_s0_minus1[0]                                    010 = 1
[trace_headers @ 000001b104a32a00] 226         used_by_curr_pic_s0_flag[0]                                 1 = 1
[trace_headers @ 000001b104a32a00] 227         delta_poc_s0_minus1[1]                                    010 = 1
[trace_headers @ 000001b104a32a00] 230         used_by_curr_pic_s0_flag[1]                                 1 = 1
[trace_headers @ 000001b104a32a00] 231         delta_poc_s0_minus1[2]                                    010 = 1
[trace_headers @ 000001b104a32a00] 234         used_by_curr_pic_s0_flag[2]                                 1 = 1
[trace_headers @ 000001b104a32a00] 235         delta_poc_s1_minus1[0]                                    010 = 1
[trace_headers @ 000001b104a32a00] 238         used_by_curr_pic_s1_flag[0]                                 1 = 1
[trace_headers @ 000001b104a32a00] 239         inter_ref_pic_set_prediction_flag                           1 = 1
[trace_headers @ 000001b104a32a00] 240         delta_rps_sign                                              0 = 0
[trace_headers @ 000001b104a32a00] 241         abs_delta_rps_minus1                                        1 = 0
[trace_headers @ 000001b104a32a00] 242         used_by_curr_pic_flag[0]                                    1 = 1
[trace_headers @ 000001b104a32a00] 243         used_by_curr_pic_flag[1]                                    1 = 1
[trace_headers @ 000001b104a32a00] 244         used_by_curr_pic_flag[2]                                    0 = 0
[trace_headers @ 000001b104a32a00] 245         use_delta_flag[2]                                           0 = 0
[trace_headers @ 000001b104a32a00] 246         used_by_curr_pic_flag[3]                                    0 = 0
[trace_headers @ 000001b104a32a00] 247         use_delta_flag[3]                                           1 = 1
[trace_headers @ 000001b104a32a00] 248         used_by_curr_pic_flag[4]                                    1 = 1
[trace_headers @ 000001b104a32a00] 249         inter_ref_pic_set_prediction_flag                           1 = 1
[trace_headers @ 000001b104a32a00] 250         delta_rps_sign                                              1 = 1
[trace_headers @ 000001b104a32a00] 251         abs_delta_rps_minus1                                      010 = 1
[trace_headers @ 000001b104a32a00] 254         used_by_curr_pic_flag[0]                                    1 = 1
[trace_headers @ 000001b104a32a00] 255         used_by_curr_pic_flag[1]                                    1 = 1
[trace_headers @ 000001b104a32a00] 256         used_by_curr_pic_flag[2]                                    1 = 1
[trace_headers @ 000001b104a32a00] 257         used_by_curr_pic_flag[3]                                    1 = 1
[trace_headers @ 000001b104a32a00] 258         used_by_curr_pic_flag[4]                                    0 = 0
[trace_headers @ 000001b104a32a00] 259         use_delta_flag[4]                                           0 = 0
[trace_headers @ 000001b104a32a00] 260         inter_ref_pic_set_prediction_flag                           0 = 0
[trace_headers @ 000001b104a32a00] 261         num_negative_pics                                         010 = 1
[trace_headers @ 000001b104a32a00] 264         num_positive_pics                                       00100 = 3
[trace_headers @ 000001b104a32a00] 269         delta_poc_s0_minus1[0]                                      1 = 0
[trace_headers @ 000001b104a32a00] 270         used_by_curr_pic_s0_flag[0]                                 1 = 1
[trace_headers @ 000001b104a32a00] 271         delta_poc_s1_minus1[0]                                      1 = 0
[trace_headers @ 000001b104a32a00] 272         used_by_curr_pic_s1_flag[0]                                 1 = 1
[trace_headers @ 000001b104a32a00] 273         delta_poc_s1_minus1[1]                                    010 = 1
[trace_headers @ 000001b104a32a00] 276         used_by_curr_pic_s1_flag[1]                                 0 = 0
[trace_headers @ 000001b104a32a00] 277         delta_poc_s1_minus1[2]                                  00100 = 3
[trace_headers @ 000001b104a32a00] 282         used_by_curr_pic_s1_flag[2]                                 0 = 0
[trace_headers @ 000001b104a32a00] 283         inter_ref_pic_set_prediction_flag                           1 = 1
[trace_headers @ 000001b104a32a00] 284         delta_rps_sign                                              1 = 1
[trace_headers @ 000001b104a32a00] 285         abs_delta_rps_minus1                                      010 = 1
[trace_headers @ 000001b104a32a00] 288         used_by_curr_pic_flag[0]                                    1 = 1
[trace_headers @ 000001b104a32a00] 289         used_by_curr_pic_flag[1]                                    1 = 1
[trace_headers @ 000001b104a32a00] 290         used_by_curr_pic_flag[2]                                    1 = 1
[trace_headers @ 000001b104a32a00] 291         used_by_curr_pic_flag[3]                                    0 = 0
[trace_headers @ 000001b104a32a00] 292         use_delta_flag[3]                                           1 = 1
[trace_headers @ 000001b104a32a00] 293         used_by_curr_pic_flag[4]                                    0 = 0
[trace_headers @ 000001b104a32a00] 294         use_delta_flag[4]                                           0 = 0
[trace_headers @ 000001b104a32a00] 295         inter_ref_pic_set_prediction_flag                           0 = 0
[trace_headers @ 000001b104a32a00] 296         num_negative_pics                                       00101 = 4
[trace_headers @ 000001b104a32a00] 301         num_positive_pics                                           1 = 0
[trace_headers @ 000001b104a32a00] 302         delta_poc_s0_minus1[0]                                0001000 = 7
[trace_headers @ 000001b104a32a00] 309         used_by_curr_pic_s0_flag[0]                                 1 = 1
[trace_headers @ 000001b104a32a00] 310         delta_poc_s0_minus1[1]                                    010 = 1
[trace_headers @ 000001b104a32a00] 313         used_by_curr_pic_s0_flag[1]                                 1 = 1
[trace_headers @ 000001b104a32a00] 314         delta_poc_s0_minus1[2]                                    010 = 1
[trace_headers @ 000001b104a32a00] 317         used_by_curr_pic_s0_flag[2]                                 1 = 1
[trace_headers @ 000001b104a32a00] 318         delta_poc_s0_minus1[3]                                    010 = 1
[trace_headers @ 000001b104a32a00] 321         used_by_curr_pic_s0_flag[3]                                 0 = 0
[trace_headers @ 000001b104a32a00] 322         inter_ref_pic_set_prediction_flag                           1 = 1
[trace_headers @ 000001b104a32a00] 323         delta_rps_sign                                              0 = 0
[trace_headers @ 000001b104a32a00] 324         abs_delta_rps_minus1                                    00100 = 3
[trace_headers @ 000001b104a32a00] 329         used_by_curr_pic_flag[0]                                    1 = 1
[trace_headers @ 000001b104a32a00] 330         used_by_curr_pic_flag[1]                                    1 = 1
[trace_headers @ 000001b104a32a00] 331         used_by_curr_pic_flag[2]                                    1 = 1
[trace_headers @ 000001b104a32a00] 332         used_by_curr_pic_flag[3]                                    0 = 0
[trace_headers @ 000001b104a32a00] 333         use_delta_flag[3]                                           0 = 0
[trace_headers @ 000001b104a32a00] 334         used_by_curr_pic_flag[4]                                    1 = 1
[trace_headers @ 000001b104a32a00] 335         inter_ref_pic_set_prediction_flag                           1 = 1
[trace_headers @ 000001b104a32a00] 336         delta_rps_sign                                              0 = 0
[trace_headers @ 000001b104a32a00] 337         abs_delta_rps_minus1                                      010 = 1
[trace_headers @ 000001b104a32a00] 340         used_by_curr_pic_flag[0]                                    1 = 1
[trace_headers @ 000001b104a32a00] 341         used_by_curr_pic_flag[1]                                    1 = 1
[trace_headers @ 000001b104a32a00] 342         used_by_curr_pic_flag[2]                                    0 = 0
[trace_headers @ 000001b104a32a00] 343         use_delta_flag[2]                                           0 = 0
[trace_headers @ 000001b104a32a00] 344         used_by_curr_pic_flag[3]                                    0 = 0
[trace_headers @ 000001b104a32a00] 345         use_delta_flag[3]                                           1 = 1
[trace_headers @ 000001b104a32a00] 346         used_by_curr_pic_flag[4]                                    1 = 1
[trace_headers @ 000001b104a32a00] 347         long_term_ref_pics_present_flag                             1 = 1
[trace_headers @ 000001b104a32a00] 348         num_long_term_ref_pics_sps                                  1 = 0
[trace_headers @ 000001b104a32a00] 349         sps_temporal_mvp_enabled_flag                               1 = 1
[trace_headers @ 000001b104a32a00] 350         strong_intra_smoothing_enabled_flag                         0 = 0
[trace_headers @ 000001b104a32a00] 351         vui_parameters_present_flag                                 1 = 1
[trace_headers @ 000001b104a32a00] 352         aspect_ratio_info_present_flag                              1 = 1
[trace_headers @ 000001b104a32a00] 353         aspect_ratio_idc                                     00000001 = 1
[trace_headers @ 000001b104a32a00] 361         overscan_info_present_flag                                  0 = 0
[trace_headers @ 000001b104a32a00] 362         video_signal_type_present_flag                              1 = 1
[trace_headers @ 000001b104a32a00] 363         video_format                                              000 = 0
[trace_headers @ 000001b104a32a00] 366         video_full_range_flag                                       0 = 0
[trace_headers @ 000001b104a32a00] 367         colour_description_present_flag                             0 = 0
[trace_headers @ 000001b104a32a00] 368         chroma_loc_info_present_flag                                0 = 0
[trace_headers @ 000001b104a32a00] 369         neutral_chroma_indication_flag                              0 = 0
[trace_headers @ 000001b104a32a00] 370         field_seq_flag                                              0 = 0
[trace_headers @ 000001b104a32a00] 371         frame_field_info_present_flag                               1 = 1
[trace_headers @ 000001b104a32a00] 372         default_display_window_flag                                 0 = 0
[trace_headers @ 000001b104a32a00] 373         vui_timing_info_present_flag                                1 = 1
[trace_headers @ 000001b104a32a00] 374         vui_num_units_in_tick        00000000000000000000000000000001 = 1
[trace_headers @ 000001b104a32a00] 406         vui_time_scale               00000000000000000000000000011101 = 29
[trace_headers @ 000001b104a32a00] 438         vui_poc_proportional_to_timing_flag                         0 = 0
[trace_headers @ 000001b104a32a00] 439         vui_hrd_parameters_present_flag                             0 = 0
[trace_headers @ 000001b104a32a00] 440         bitstream_restriction_flag                                  0 = 0
[trace_headers @ 000001b104a32a00] 441         sps_extension_present_flag                                  0 = 0
[trace_headers @ 000001b104a32a00] 442         rbsp_stop_one_bit                                           1 = 1
[trace_headers @ 000001b104a32a00] 443         rbsp_alignment_zero_bit                                     0 = 0
[trace_headers @ 000001b104a32a00] 444         rbsp_alignment_zero_bit                                     0 = 0
[trace_headers @ 000001b104a32a00] 445         rbsp_alignment_zero_bit                                     0 = 0
[trace_headers @ 000001b104a32a00] 446         rbsp_alignment_zero_bit                                     0 = 0
[trace_headers @ 000001b104a32a00] 447         rbsp_alignment_zero_bit                                     0 = 0
[trace_headers @ 000001b104a32a00] Picture Parameter Set
[trace_headers @ 000001b104a32a00] 0           forbidden_zero_bit                                          0 = 0
[trace_headers @ 000001b104a32a00] 1           nal_unit_type                                          100010 = 34
[trace_headers @ 000001b104a32a00] 7           nuh_layer_id                                           000000 = 0
[trace_headers @ 000001b104a32a00] 13          nuh_temporal_id_plus1                                     001 = 1
[trace_headers @ 000001b104a32a00] 16          pps_pic_parameter_set_id                                    1 = 0
[trace_headers @ 000001b104a32a00] 17          pps_seq_parameter_set_id                                    1 = 0
[trace_headers @ 000001b104a32a00] 18          dependent_slice_segments_enabled_flag                       0 = 0
[trace_headers @ 000001b104a32a00] 19          output_flag_present_flag                                    0 = 0
[trace_headers @ 000001b104a32a00] 20          num_extra_slice_header_bits                               000 = 0
[trace_headers @ 000001b104a32a00] 23          sign_data_hiding_enabled_flag                               0 = 0
[trace_headers @ 000001b104a32a00] 24          cabac_init_present_flag                                     0 = 0
[trace_headers @ 000001b104a32a00] 25          num_ref_idx_l0_default_active_minus1                      011 = 2
[trace_headers @ 000001b104a32a00] 28          num_ref_idx_l1_default_active_minus1                        1 = 0
[trace_headers @ 000001b104a32a00] 29          init_qp_minus26                                       0001110 = 7
[trace_headers @ 000001b104a32a00] 36          constrained_intra_pred_flag                                 0 = 0
[trace_headers @ 000001b104a32a00] 37          transform_skip_enabled_flag                                 1 = 1
[trace_headers @ 000001b104a32a00] 38          cu_qp_delta_enabled_flag                                    0 = 0
[trace_headers @ 000001b104a32a00] 39          pps_cb_qp_offset                                            1 = 0
[trace_headers @ 000001b104a32a00] 40          pps_cr_qp_offset                                            1 = 0
[trace_headers @ 000001b104a32a00] 41          pps_slice_chroma_qp_offsets_present_flag                    0 = 0
[trace_headers @ 000001b104a32a00] 42          weighted_pred_flag                                          0 = 0
[trace_headers @ 000001b104a32a00] 43          weighted_bipred_flag                                        0 = 0
[trace_headers @ 000001b104a32a00] 44          transquant_bypass_enabled_flag                              0 = 0
[trace_headers @ 000001b104a32a00] 45          tiles_enabled_flag                                          0 = 0
[trace_headers @ 000001b104a32a00] 46          entropy_coding_sync_enabled_flag                            0 = 0
[trace_headers @ 000001b104a32a00] 47          pps_loop_filter_across_slices_enabled_flag                  1 = 1
[trace_headers @ 000001b104a32a00] 48          deblocking_filter_control_present_flag                      1 = 1
[trace_headers @ 000001b104a32a00] 49          deblocking_filter_override_enabled_flag                     1 = 1
[trace_headers @ 000001b104a32a00] 50          pps_deblocking_filter_disabled_flag                         0 = 0
[trace_headers @ 000001b104a32a00] 51          pps_beta_offset_div2                                        1 = 0
[trace_headers @ 000001b104a32a00] 52          pps_tc_offset_div2                                          1 = 0
[trace_headers @ 000001b104a32a00] 53          pps_scaling_list_data_present_flag                          0 = 0
[trace_headers @ 000001b104a32a00] 54          lists_modification_present_flag                             1 = 1
[trace_headers @ 000001b104a32a00] 55          log2_parallel_merge_level_minus2                            1 = 0
[trace_headers @ 000001b104a32a00] 56          slice_segment_header_extension_present_flag                 0 = 0
[trace_headers @ 000001b104a32a00] 57          pps_extension_present_flag                                  0 = 0
[trace_headers @ 000001b104a32a00] 58          rbsp_stop_one_bit                                           1 = 1
[trace_headers @ 000001b104a32a00] 59          rbsp_alignment_zero_bit                                     0 = 0
[trace_headers @ 000001b104a32a00] 60          rbsp_alignment_zero_bit                                     0 = 0
[trace_headers @ 000001b104a32a00] 61          rbsp_alignment_zero_bit                                     0 = 0
[trace_headers @ 000001b104a32a00] 62          rbsp_alignment_zero_bit                                     0 = 0
[trace_headers @ 000001b104a32a00] 63          rbsp_alignment_zero_bit                                     0 = 0
[trace_headers @ 000001b104a32a00] Prefix Supplemental Enhancement Information
[trace_headers @ 000001b104a32a00] 0           forbidden_zero_bit                                          0 = 0
[trace_headers @ 000001b104a32a00] 1           nal_unit_type                                          100111 = 39
[trace_headers @ 000001b104a32a00] 7           nuh_layer_id                                           000000 = 0
[trace_headers @ 000001b104a32a00] 13          nuh_temporal_id_plus1                                     001 = 1
[trace_headers @ 000001b104a32a00] 16          last_payload_type_byte                               00000001 = 1
[trace_headers @ 000001b104a32a00] 24          last_payload_size_byte                               00000001 = 1
[trace_headers @ 000001b104a32a00] Picture Timing
[trace_headers @ 000001b104a32a00] 32          pic_struct                                               0000 = 0
[trace_headers @ 000001b104a32a00] 36          source_scan_type                                           01 = 1
[trace_headers @ 000001b104a32a00] 38          duplicate_flag                                              0 = 0
[trace_headers @ 000001b104a32a00] 39          bit_equal_to_one                                            1 = 1
[trace_headers @ 000001b104a32a00] 40          rbsp_stop_one_bit                                           1 = 1
[trace_headers @ 000001b104a32a00] 41          rbsp_alignment_zero_bit                                     0 = 0
[trace_headers @ 000001b104a32a00] 42          rbsp_alignment_zero_bit                                     0 = 0
[trace_headers @ 000001b104a32a00] 43          rbsp_alignment_zero_bit                                     0 = 0
[trace_headers @ 000001b104a32a00] 44          rbsp_alignment_zero_bit                                     0 = 0
[trace_headers @ 000001b104a32a00] 45          rbsp_alignment_zero_bit                                     0 = 0
[trace_headers @ 000001b104a32a00] 46          rbsp_alignment_zero_bit                                     0 = 0
[trace_headers @ 000001b104a32a00] 47          rbsp_alignment_zero_bit                                     0 = 0
```
</details>

```
...
[trace_headers @ 000001b104a32a00] Filler Data
[trace_headers @ 000001b104a32a00] 0           forbidden_zero_bit                                          0 = 0
[trace_headers @ 000001b104a32a00] 1           nal_unit_type                                          100110 = 38
[trace_headers @ 000001b104a32a00] 7           nuh_layer_id                                           000000 = 0
[trace_headers @ 000001b104a32a00] 13          nuh_temporal_id_plus1                                     001 = 1
[trace_headers @ 000001b104a32a00] 16          rbsp_stop_one_bit                                           1 = 1
[trace_headers @ 000001b104a32a00] 17          rbsp_alignment_zero_bit                                     0 = 0
[trace_headers @ 000001b104a32a00] 18          rbsp_alignment_zero_bit                                     1 = 1
[trace_headers @ 000001b104a32a00] rbsp_alignment_zero_bit out of range: 1, but must be in [0,0].
[trace_headers @ 000001b104a32a00] Failed to read unit 4 (type 38).
```

### PR DESCRIPTION
**Pull request by ha-ves**
I read a bit [RFC 7798 Section 4.4](https://datatracker.ietf.org/doc/html/rfc7798#section-4.4)

Summary:
- The NAL parser forgot to set `zeroes` back to 0,
- The aggregator forgot to return aggregated NALs,
- Use a semantically readable fragmentation NAL (FU) handling

fixes #1392 
forwards https://github.com/sipsorcery-org/SIPSorceryMedia.FFmpeg/pull/97

### CODE REVIEW

**Comment by sipsorcery** [comment]
@ha-ves this PR does not build for me. 

`The name '_pktCounter' does not exist in the current context`

**Comment by ha-ves** [comment]
@sipsorcery Sorry, leftover stats logging. 

All examples and tests with browser peers are pending since they don't support HEVC/H.265, so there will be no correctly negotiated format.

I was testing in WPF. I could add it as an example with this PR, I'll have to clean it up a bit.
The test in summary:
```c#
var it = new FFmpegFileSource("max_intro.mp4", true, null);

var ti = new FFmpegVideoEndPoint();

///...
// assign endpoint event to copy to wiretablebitmap backbuffer, etc.
///...

it.RestrictFormats(f => f.Codec == VideoCodecsEnum.H265);
it.SetVideoSourceFormat(it.GetVideoSourceFormats().First());

/// ...
// create 2 PC,
// assign events, add tracks, signaling, etc.,
/// ...

while (pcrmt.connectionState != RTCPeerConnectionState.connected
    || pclcl.connectionState != RTCPeerConnectionState.connected)
    Thread.Sleep(1000);

it.StartVideo();
```

**Comment by jimm98y** [comment]
"All examples and tests with browser peers are pending since they don't support HEVC/H.265"
Actually, Safari on iOS/MacOS has supported H265 in WebRTC for a few months already and now the latest Chrome 136 also supports H265 in WebRTC. The requirement for it to work is to have a HW HEVC decoder, it does not work with software decoding. Most GPUs today should support it.

**Comment by sipsorcery** [comment]
As @jimm98y says Chrome has [announced](https://chromestatus.com/feature/5153479456456704) support from version 136. I was on v135 but a pending update got me to v136. I then did try and test H265 again but it seems my GPU does not have a H265 codec.

My iPhone does advertise H265 but it's a bit tricky to test on with my network set up.

Given H265 support is still brand new in most cases I think it's safe enough to merge this PR. That will make it easier to test and add additional fixes if needs be.

**Review by sipsorcery — APPROVED** [review]

File: src/net/RTP/VideoStream.cs [hunk 1]
```diff
@@ -203,9 +207,18 @@ public void SendH265Frame(uint durationRtpUnits, int payloadID, byte[] sample)
...
                 var nals = H265Packetiser.ParseNals(sample);
-                var aggregatedNals = H265Packetiser.CreateAggregated(nals, RTPSession.RTP_MAX_PAYLOAD);
-                foreach (var nal in aggregatedNals)
+
+                // aggregation is only on 2 or more small nals
+                if (nals.Where(x => x.NAL.Length < RTPSession.RTP_MAX_PAYLOAD).Count() > 1)
+                {
+                    //logger.LogTrace("(ou) Trying aggregating {nals} nals", nals.Count());
+                    nals = H265Packetiser.CreateAggregated(nals, RTPSession.RTP_MAX_PAYLOAD);
+                }
```
Comment (paulomorgado) [inline src/net/RTP/VideoStream.cs:216]: `Any` will only cause the `nals` sequence to be iterated until the first is found, while `Count` will cause the `nals` sequence to be completely iterated.

Both incur in delegate allocation (although in the latest SDKs this may be a static delegate instance) and invocation.

I would prefer something like:

``csharp
                foreach (var nal in nals)
                {
                    if (nal.NAL.Length< RTPSession.RTP_MAX_PAYLOAD)
                    {
                        nals = H265Packetiser.CreateAggregated(nals, RTPSession.RTP_MAX_PAYLOAD);
                        break;
                    }
                }
```
