### PR TITLE
Fixed race-condition in RTP SeqNum generation. Resolves #484.

### LINKED ISSUE #484: RTP Seq is sometimes used twice when sending DTMF due to race condition
I encountered the following duplicate Seq Number for an RTP Event rsp. a skipped Seq Number when sending DTMF RTP-Events using the userAgend.SendDtmf Method.

image

The cause is the non-synchronized increments of the audioTrack.SeqNum Property. Without DTMF, this is never a problem, because only one thread is ever incrementing the SeqNum. But if SendDTMF is called, another Thread is introduced, which introduces the observer Race-Condition (classic read, modify write problem).

To avoid having to use an expensive lock statement when incrementing the SeqNum, I propose the folowing solution:

Replace property `MediaStreamTrack.SeqNum` with a private field. Change all accesses to `MediaStreamTrack.SeqNum` to a Method call `GetNextSeqNum`, which increments and returns a `SeqNum` to use when creating a `RTPPacket`. `GetNextSeqNum` should increment the new field using `Interlocked.CompareExchange` using something like https://stackoverflow.com/a/8698560 to faciliate the integer overflow.

This would also remove all the lines 
`audioTrack.SeqNum = (audioTrack.SeqNum == UInt16.MaxValue) ? (ushort)0 : (ushort)(audioTrack.SeqNum + 1);` from RTPSession, and centralise the incrementing and overflow handling to the new method GetNextSeqNum.

If its okay with @sipsorcery , I will prepare a Pull Request with the before mentioned changes. Or do you have another preferred way to solve this?

Regards,
Tobias

### PR DESCRIPTION
**Pull request by tstaehli**
Pull Request for issue #484.
I'm not sure if it is OK to remove to public property SeqNum; but since none of the examples explicitly use it and I don't really see a usecase for accessing this property other than in the RTPSession class, I removed it.

### CODE REVIEW

File: src/net/RTP/MediaStreamTrack.cs [hunk 1]
```diff
@@ -262,5 +263,23 @@ public bool IsSsrcMatch(uint ssrc)
...
+        public ushort GetNextSeqNum()
+        {
+            var actualSeqNum = m_seqNum;
+            int expectedSeqNum;
+            do
+            {
+                expectedSeqNum = actualSeqNum;
+                int nextSeqNum = (actualSeqNum >= UInt16.MaxValue) ? (ushort)0 : (ushort)(actualSeqNum + 1);
+                actualSeqNum = Interlocked.CompareExchange(ref m_seqNum, nextSeqNum, expectedSeqNum);
+            } while (expectedSeqNum != actualSeqNum); // Try as long as compare-exchange was not successful; in most cases, only one iteration should be needed
```
Comment (sipsorcery) [inline src/net/RTP/MediaStreamTrack.cs:281]: It would be nice to have a safety valve here to avoid any possibility of an infinite loop. I usually use something like an "attempts" variable and if it reaches 10 exit and throw an exception.

Comment (tstaehli) [reply src/net/RTP/MediaStreamTrack.cs:286]: Altough I don't think the safety valve will ever trigger(or if it does, something else is most likely a problem), it should not hurt performance, because this is only a local variable.
